### ISSUE TITLE
Is there any way to contact you?

### ISSUE THREAD

**Issue by Duck-Hunter** [daijro/SearchifyX#9]

**Comment by daijro** [comment]
Hello!
I considered adding ChatGPT to the UI, but Merlin has a limitation of 20 queries per limit. Because of this, I chose not to add it into the UI yet. I will consider transferring to the pyChatGPT API though! Right now I'm working on optimizing/updating the backend as much as I can before I focus my attention back to the UI

You can contact me through here on GitHub issues or at my email, daijro.dev@gmail.com. I have been busy with school work recently, so unfortunately I won't be able to respond quickly.

Thanks!
